# Generated by Django 3.1.5 on 2021-02-08 19:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('RiseApp_Teams', '0002_auto_20210208_1901'),
        ('RiseApp_Projects', '0004_auto_20210208_1904'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='team',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='RiseApp_Teams.team'),
        ),
    ]
