# Generated by Django 3.1.1 on 2020-10-23 06:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, null=True)),
                ('projectTitle', models.CharField(max_length=13)),
                ('StartDate', models.DateTimeField(verbose_name='StartDate')),
                ('EndDate', models.DateTimeField(verbose_name='EndDate')),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TeamName', models.CharField(max_length=20)),
                ('SizeOfTeam', models.IntegerField()),
                ('TeamMember', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Timer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('StartTime', models.TimeField(auto_now_add='true')),
                ('EndTime', models.TimeField(auto_now='true')),
                ('TotalTime', models.TimeField(default='true')),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_name', models.CharField(max_length=13)),
                ('task_description', models.TextField(blank=True, null=True)),
                ('created_date', models.DateTimeField(verbose_name='created_date')),
                ('finished_date', models.DateTimeField(verbose_name='finished_date')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RiseApp.project')),
            ],
        ),
    ]
