# Generated by Django 3.1.1 on 2020-11-12 03:33

import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('RiseApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='auth.user')),
                ('role', models.PositiveBigIntegerField(blank=True, choices=[(1, 'project manager'), (2, 'frontend designer'), (3, 'frontend developer'), (4, 'backend developer'), (5, 'fullstack developer'), (6, 'systems engineer'), (7, 'senior software engineer'), (8, 'software engineer'), (9, 'junior software engineer'), (10, 'mobile app designer'), (11, 'mobile app developer'), (12, 'android developer'), (13, 'ios developer'), (14, 'web developer')], null=True)),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.DeleteModel(
            name='Team',
        ),
    ]
