# Generated by Django 3.1.1 on 2020-11-20 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RiseApp', '0003_team'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='Team_id',
            field=models.IntegerField(default=1),
        ),
    ]
