# Generated by Django 3.1.1 on 2020-11-20 05:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('RiseApp', '0005_teammember_team'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='project',
        ),
        migrations.AddField(
            model_name='project',
            name='title',
            field=models.CharField(blank=True, max_length=35),
        ),
        migrations.AlterField(
            model_name='team',
            name='Team_id',
            field=models.IntegerField(verbose_name='id:'),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RiseApp.team'),
        ),
    ]
