# Generated by Django 3.1.1 on 2020-11-20 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RiseApp', '0006_auto_20201120_0505'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='title',
        ),
        migrations.AlterField(
            model_name='project',
            name='projectTitle',
            field=models.CharField(max_length=18),
        ),
    ]
